version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cognito-apigateway-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1itbpbaza7j6c"
s3_prefix = "cognito-apigateway-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Client=\"https://myapp.com\" TestWithPostman=\"true\""
image_repositories = []
