version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cognito-ecs-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1q26kcfv0s3z8"
s3_prefix = "cognito-ecs-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "pVpcId=\"vpc-01a81eec6eexample\" pPrivateSubnetIds=\"subnet-0b58b8b621example,subnet-0f56f9b73example\" pCIDRRange=\"10.0.0.0/8\""
image_repositories = []
